package rdw_opendata_go

type RegisteredVehicle struct {
	LicensePlate                         string `json:"kenteken"`
	VehicleType                          string `json:"voertuigsoort"`
	Brand                                string `json:"merk"`
	TradeName                            string `json:"handelsbenaming"`
	ExpirationDateMOT                    string `json:"vervaldatum_apk"`
	DateOfAscription                     string `json:"datum_tenaamstelling"`
	Interior                             string `json:"inrichting"`
	NumberOfSeats                        string `json:"aantal_zitplaatsen"`
	PrimaryColor                         string `json:"eerste_kleur"`
	SecondaryColor                       string `json:"tweede_kleur"`
	MassEmptyVehicle                     string `json:"massa_ledig_voertuig"`
	AllowedMaximumMassVehicle            string `json:"toegestane_maximum_massa_voertuig"`
	MassRoadworthy                       string `json:"massa_rijklaar"`
	MaximumMassPullingUninhibited        string `json:"maximum_massa_trekken_ongeremd"`
	MaximumMassPullingInhibited          string `json:"maximum_trekken_massa_geremd"`
	TechnicalMaximumMassVehicle          string `json:"technische_max_massa_voertuig"`
	DateOfFirstAdmission                 string `json:"datum_eerste_toelating"`
	DateOfFirstAscriptionNL              string `json:"datum_eerste_tenaamstelling_in_nederland"`
	CatalogPrice                         string `json:"catalogusprijs"`
	MaximumConstructionSpeed             string `json:"maximum_constructiesnelheid"`
	NumberOfDoors                        string `json:"aantal_deuren"`
	NumberOfWheels                       string `json:"aantal_wielen"`
	DistanceCentreCouplingToRearVehicle  string `json:"afstand_hart_koppeling_tot_achterzijde_voertuig"`
	DistanceFrontVehicleToCentreCoupling string `json:"afstand_voorzijde_voertuig_tot_hart_koppeling"`
	Length                               string `json:"lengte"`
	Width                                string `json:"breedte"`
	Wheelbase                            string `json:"wielbasis"`
	Height                               string `json:"hoogte"`
	EuropeanVehicleCategory              string `json:"europese_voertuigcategorie"`
	EuropeanVehicleCategoryAddition      string `json:"europese_voertuigcategorie_toevoeging"`
	EuropeanExecutionCategoryAddition    string `json:"europese_uitvoeringcategorie_toevoeging"`
	LocationChassisNumber                string `json:"plaats_chassisnummer"`
	Type                                 string `json:"type"`
	TypeApprovalNumber                   string `json:"typegoedkeuringsnummer"`
	Variant                              string `json:"variant"`
	Version                              string `json:"uitvoering"`
	SerialNumberChangeEUTypeApproval     string `json:"volgnummer_wijziging_eu_typegoedkeuring"`
	PowerMassRoadworthy                  string `json:"vermogen_massarijklaar"`
	ExportIndicator                      string `json:"export_indicator"`
	RecallIndicator                      string `json:"openstaande_terugroepactie_indicator"`
	TaxiIndicator                        string `json:"taxi_indicator"`
	MileageJudgement                     string `json:"tellerstandoordeel"`
	MileageJudgementCode                 string `json:"code_toelichting_tellerstandoordeel"`
	MileageLastRegistrationYear          string `json:"jaar_laatste_registratie_tellerstand"`
	RegistrationPossible                 string `json:"tenaamstellen_mogelijk"`
}
